---
- name: Create stack root directory
  file:
    path: "{{ reverse_proxy_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create reverse_proxy directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"
  loop:
    - "{{ swag_config_path }}"
    - "{{ duckdns_config_path }}"
    - "{{ authelia_config_path }}"
    - "{{ heimdall_config_path }}"
    - "{{ heimdall_config_path }}/www"
    - "{{ heimdall_config_path }}/www/SupportedApps"
    - "{{ heimdall_config_path }}/www/icons"
    - "/tmp/heimdall-support"

- name: Copy Heimdall database
  copy:
    src: heimdall-app.sqlite
    dest: "{{ heimdall_config_path }}/www/app.sqlite"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy Heimdall support files (local:remote)
  unarchive:
    src: heimdall-support/bundle.tar.gz
    dest: /tmp/heimdall-support/
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy Heimdall support files (remote:remote)
  copy:
    src: "/tmp/heimdall-support/{{ item }}/"
    remote_src: yes
    dest: "{{ heimdall_config_path }}/www/{{ item }}/"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"
  loop:
    - SupportedApps
    - icons

- name: Installing sqlit3 for heimdall data injection
  apt:
    name: sqlite3
    update_cache: yes

- name: Insert Heimdall items
  script:
    cmd: "update-heimdall-db.sh {{ heimdall_config_path }} {{ server_domain_name }} {{ item.name }}"
  with_list: "{{ reverse_proxy_app_list | selectattr('heimdall_enable', '==', true) | list}}"

- name: Configure Authelia
  block:
    - name: Setting facts for Authelia secret keys
      set_fact:
        authelia_jwt_secret: "{{ lookup('password', 'api-keys-temp/authelia_jwt_secret chars=ascii_lowercase length=30') }}"
        authelia_session_secret: "{{ lookup('password', 'api-keys-temp/authelia_session_secret chars=ascii_lowercase length=16') }}"
        authelia_storage_secret: "{{ lookup('password', 'api-keys-temp/authelia_storage_secret chars=ascii_lowercase length=24') }}"

    - name: Generate the Authelia user password hash
      script:
        cmd: "authelia-generate-password-hash.sh {{ authelia_user_password }}"
      register: authelia_user_password_hash

    - name: Copy Authelia configs
      template:
        src: "authelia/{{ item }}.j2"
        dest: "{{ authelia_config_path }}/{{ item }}"
      loop:
        - "configuration.yml"
        - "users_database.yml"
  when: authelia_enable|bool == true

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ reverse_proxy_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Start Docker containers using docker-compose
  community.docker.docker_compose:
    project_src: "{{ reverse_proxy_container_stack_location }}"
  tags: start-stacks

- name: Wait until Swag container up and create subfolder configs
  wait_for:
    path: "{{ swag_config_path }}/nginx/proxy-confs/{{ item.name }}.{{ item.type }}.conf.sample"
  with_list: "{{ reverse_proxy_app_list | selectattr('proxy_conf_enable', '==', true) | list}}"

- name: Wait until Swag container up and create default config
  wait_for:
    path: "{{ swag_config_path }}/nginx/site-confs/default"

- name: Adding subdomain reverse proxy configuration
  copy:
    src: "{{ swag_config_path }}/nginx/proxy-confs/{{ item.name }}.{{ item.type }}.conf.sample"
    dest: "{{ swag_config_path }}/nginx/proxy-confs/{{ item.name }}.{{ item.type }}.conf"
    remote_src: yes
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"
  with_list: "{{ reverse_proxy_app_list | selectattr('proxy_conf_enable', '==', true) | list}}"

- name: Set subdomain app name to vpn container for transmission
  replace:
    path: "{{ swag_config_path }}/nginx/proxy-confs/transmission.subdomain.conf"
    regexp: '^\s+set $upstream_app transmission;$'
    replace: "        set $upstream_app vpn;"
  when: add_vpn_container|bool == true and transmission_enable|bool == true

- name: Set subdomain app name to vpn container for qbittorrent
  replace:
    path: "{{ swag_config_path }}/nginx/proxy-confs/qbittorrent.subdomain.conf"
    regexp: '^\s+set $upstream_app qbittorrent;$'
    replace: "        set $upstream_app vpn;"
  when: add_vpn_container|bool == true and qbittorrent_enable|bool == true

- name: Enabling Authelia server for apps
  replace:
    path: "{{ swag_config_path }}/nginx/proxy-confs/{{ item.name }}.{{ item.type }}.conf"
    regexp: '^\s+\#include /config/nginx/authelia-server.conf;$'
    replace: "    include /config/nginx/authelia-server.conf;"
  with_list: "{{ reverse_proxy_app_list | selectattr('proxy_conf_enable', '==', true) | list}}"
  when: authelia_enable|bool == true

- name: Enabling Authelia location for apps
  replace:
    path: "{{ swag_config_path }}/nginx/proxy-confs/{{ item.name }}.{{ item.type }}.conf"
    regexp: '^\s+\#include /config/nginx/authelia-location.conf;$'
    replace: "    include /config/nginx/authelia-location.conf;"
  with_list: "{{ reverse_proxy_app_list | selectattr('proxy_conf_enable', '==', true) | list}}"
  when: authelia_enable|bool == true

- name: Correct the incorrect server_name for uptime-kuma
  lineinfile:
    path: "{{ swag_config_path }}/nginx/proxy-confs/uptime-kuma.subdomain.conf"
    regexp: '^\s+server_name uptime.\*;$'
    line: "    server_name uptime-kuma.*;"

- name: Install new nginx config
  template:
    src: nginx-server.conf.j2
    dest: "{{ swag_config_path }}/nginx/site-confs/default"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Restart Docker containers using docker-compose
  community.docker.docker_compose:
    project_src: "{{ reverse_proxy_container_stack_location }}"
    restarted: yes

- name: Stop Docker containers if running
  block:
    - name: Check wether the docker file exist
      stat:
        path: "{{ reverse_proxy_container_stack_location }}/docker-compose.yml"
      register: reverse_proxy_container_stack_location_docker_compose_file

    - name: Check validity of compose file
      shell: "docker-compose -f {{ reverse_proxy_container_stack_location }}/docker-compose.yml config"
      register: reverse_proxy_container_stack_docker_compose_file_validate
      ignore_errors: yes

    - name: Stopping using docker compose
      community.docker.docker_compose:
        project_src: "{{ reverse_proxy_container_stack_location }}"
        state: absent
      when: reverse_proxy_container_stack_location_docker_compose_file.stat.exists and reverse_proxy_container_stack_docker_compose_file_validate.failed|bool != true
  tags: [ 'never', 'stop-stacks' ]