---
- name: Create stack root directory
  file:
    path: "{{ monitoring_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create uptime-kuma directories
  file:
    path: "{{ uptime_kuma_config_path }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Start Docker containers using docker-compose
  community.docker.docker_compose:
    project_src: "{{ monitoring_container_stack_location }}"
  tags: start-stacks

- name: Stop Docker containers if running
  block:
    - name: Check wether the docker file exist
      stat:
        path: "{{ monitoring_container_stack_location }}/docker-compose.yml"
      register: monitoring_container_stack_location_docker_compose_file

    - name: Check validity of compose file
      shell: "docker-compose -f {{ monitoring_container_stack_location }}/docker-compose.yml config"
      register: monitoring_container_stack_docker_compose_file_validate
      ignore_errors: yes

    - name: Stopping using docker compose
      community.docker.docker_compose:
        project_src: "{{ monitoring_container_stack_location }}"
        state: absent
      when: monitoring_container_stack_location_docker_compose_file.stat.exists and monitoring_container_stack_docker_compose_file_validate.failed|bool != true
  tags: [ 'never', 'stop-stacks' ]