---
# GLOBAL
gv_server_timezone: Europe/Amsterdam

# Docker
gv_docker_bridge_network_name: media-server-network

# USER
ansible_user: pi
gv_local_media_user: media-user
gv_local_media_uid: 1003
gv_local_media_group: media-group
gv_local_media_gid: 1002
gv_local_media_user_home: "/home/{{ gv_local_media_user }}"

# NFS
gv_nfs_server_address: freenas.local

gv_media_data_root_local_mount_path: /mnt/media_share
gv_media_data_remote_path: /mnt/media-pool/media-test

gv_server_data_root_local_mount_path: /mnt/server_data
gv_server_data_remote_path: /mnt/media-pool/media-server-data-test

# COMMON
gv_media_download_path: "{{ gv_media_data_root_local_mount_path}}/downloads"
gv_container_data_dir_name: container_data
gv_container_data_root: "{{ gv_server_data_root_local_mount_path }}/{{ gv_container_data_dir_name | default('container_data') }}"

# VPN
GV_VPN_USERNAME: your-email-address
GV_VPN_PASSWORD: your-vpn-password
GV_VPN_NETWORK_ALLOW_CIDR: 192.168.178.0/24
gv_add_vpn_container: true

# TRANSMISSION
GV_TRANSMISSION_USERNAME: "{{ gv_local_media_user }}"
GV_TRANSMISSION_PASSWORD: your-transmission-password
GV_TRANSMISSION_RPC_WHITELIST: 127.0.0.1,192.168.*.*

# Reverse Proxy
gv_server_domain_name: update-your-hostname-created-via.duckdns.org
gv_notification_email: your-email-to-receive-ssl-cert-expiration-notification@gmail.com

# DNS
gv_duckdns_token: bffc2f6e-6ce1-11ec-90d6-0242ac120003



