---
# GLOBAL
gv_server_timezone: Europe/Amsterdam

# Docker
gv_docker_bridge_network_name: media-server-network

# USER
ansible_user: pi
gv_local_media_user: media-user
gv_local_media_uid: 1003
gv_local_media_group: media-group
gv_local_media_gid: 1002
gv_local_media_user_home: "/home/{{ gv_local_media_user }}"

# Storage location type. Options : [local, nfs]
gv_storage_location_type: local

## LOCAL
gv_media_data_root_local_mount_path: /mnt/media_share
gv_server_data_root_local_mount_path: /mnt/server_data

## NFS - uncomment and configure following for NFS

#gv_nfs_server_address: freenas.local
#gv_media_data_root_local_mount_path: /mnt/media_share
#gv_media_data_remote_path: /mnt/media-pool/dutchhome-media
#gv_server_data_root_local_mount_path: /mnt/server_data
#gv_server_data_remote_path: /mnt/NAS-root/dutchhome-server-data

# COMMON
gv_container_data_dir_name: container_data
gv_container_data_root: "{{ gv_server_data_root_local_mount_path }}/{{ gv_container_data_dir_name | default('container_data') }}"

# Torrent client
gv_transmission_enable: true
gv_qbittorrent_enable: false

# VPN - only supports nordvpn
gv_add_vpn_container: false
#gv_vpn_token: <create-your-token-from-nordvpn-website>
#gv_vpn_network_allow_cidr: 192.168.178.0/24

# Reverse Proxy
gv_server_domain_name: my-hostname.duckdns.org
gv_notification_email: myemail@gmail.com

# Following has to set to false once initial testing is done
gv_use_lets_encrypt_staging_server: true

# DNS
gv_duckdns_token: 69569af6-57bb-4bef-a13b-5bb2c4807502

# Dashboard
gv_authelia_enable: true
gv_dashboard_username: my-username
gv_dashboard_password: my-password
gv_dashboard_user_email: myemail@gmail.com

