---
- name: Create stack root directory
  file:
    path: "{{ media_server_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create qbittorrent directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"
  loop:
    - "{{ qbittorrent_download_path }}"
    - "{{ qbittorrent_config_path }}"
  when: qbittorrent_enable|bool == true

- name: Install 7z to unpack rar files
  apt:
    name: [p7zip-full, p7zip]
    update_cache: yes

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ media_server_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy environment variable file
  template:
    src: .env.j2
    dest: "{{ media_server_container_stack_location }}/.env"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"
  when: add_vpn_container|bool == true

- name: Install Transmission
  block:
    - name: Create transmission directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ server_data_dir_user }}"
        group: "{{ server_data_dir_group }}"
      loop:
        - "{{ transmission_download_path }}"
        - "{{ transmission_config_path }}/scripts"

    - name: Copy transmission settings file
      template:
        src: settings.json.j2
        dest: "{{ transmission_config_path }}/settings.json"
        owner: "{{ server_data_dir_user }}"
        group: "{{ server_data_dir_group }}"

    - name: Copy transmission post download script file
      copy:
        src: post-torrent-download.sh
        dest: "{{ transmission_config_path }}/scripts/post-torrent-download.sh"
        owner: "{{ server_data_dir_user }}"
        group: "{{ server_data_dir_group }}"
        mode: '0755'
  when: transmission_enable|bool == true

- name: Create container directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"
  loop:
    - "{{ sonarr_config_path }}"
    - "{{ sonarr_library_path }}"
    - "{{ sonarr_download_path }}"
    - "{{ radarr_config_path }}"
    - "{{ radarr_library_path }}"
    - "{{ radarr_download_path }}"
    - "{{ jackett_config_path }}"
    - "{{ jackett_torrent_file_path }}"
    - "{{ jackett_config_path }}/Jackett"

- set_fact:
    sonarr_api_key: "{{ lookup('password', 'api-keys-temp/sonarr chars=ascii_lowercase,digits length=32') }}"
    radarr_api_key: "{{ lookup('password', 'api-keys-temp/radarr chars=ascii_lowercase,digits length=32') }}"
    jackett_instance_id: "{{ lookup('password', 'api-keys-temp/jackett chars=ascii_lowercase,digits length=64') }}"

- name: Copy Sonarr, Radarr config files
  template:
    src: "{{ item.name }}-config.xml.j2"
    dest: "{{ item.configPath }}/config.xml"
  loop:
    - { name: 'sonarr', configPath: "{{ sonarr_config_path }}" }
    - { name: 'radarr', configPath: "{{ radarr_config_path }}" }

- name: Copy Jackett config file
  template:
    src: jackett-config.json.j2
    dest: "{{ jackett_config_path }}/Jackett/ServerConfig.json"

- name: Start Docker containers using docker-compose
  community.docker.docker_compose:
    project_src: "{{ media_server_container_stack_location }}"
  tags: start-stacks

- name: Stop Docker containers if running
  block:
    - name: Check wether the docker file exist
      stat:
        path: "{{ media_server_container_stack_location }}/docker-compose.yml"
      register: media_server_container_stack_location_docker_compose_file

    - name: Check validity of compose file
      shell: "docker-compose -f {{ media_server_container_stack_location }}/docker-compose.yml config"
      register: media_server_container_stack_docker_compose_file_validate
      ignore_errors: yes

    - name: Stopping using docker compose
      community.docker.docker_compose:
        project_src: "{{ media_server_container_stack_location }}"
        state: absent
      when: media_server_container_stack_location_docker_compose_file.stat.exists and media_server_container_stack_docker_compose_file_validate.failed|bool != true
  tags: [ 'never', 'stop-stacks' ]


