---
- name: Create stack root directory
  file:
    path: "{{ media_server_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Create qbittorrent directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"
  loop:
    - "{{ qbittorrent_download_path }}"
    - "{{ qbittorrent_config_path }}"
  when: qbittorrent_enable|bool == true

- name: Install 7z to unpack rar files
  apt:
    name: [p7zip-full, p7zip]
    update_cache: yes

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ media_server_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy environment variable file
  template:
    src: .env.j2
    dest: "{{ media_server_container_stack_location }}/.env"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Install Transmission
  block:
    - name: Create transmission directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ server_data_dir_user }}"
        group: "{{ server_data_dir_group }}"
      loop:
        - "{{ transmission_download_path }}"
        - "{{ transmission_config_path }}/scripts"

    - name: Copy transmission settings file
      template:
        src: settings.json.j2
        dest: "{{ transmission_config_path }}/settings.json.j2"
        owner: "{{ server_data_dir_user }}"
        group: "{{ server_data_dir_group }}"

    - name: Copy transmission post download script file
      copy:
        src: post-torrent-download.sh
        dest: "{{ transmission_config_path }}/scripts/post-torrent-download.sh"
        owner: "{{ server_data_dir_user }}"
        group: "{{ server_data_dir_group }}"
        mode: '0755'
  when: transmission_enable|bool == true
  tags: test

- name: Start Docker containers using docker-compose
  community.docker.docker_compose:
    project_src: "{{ media_server_container_stack_location }}"

