---
- name: Create the mount directory
  file:
    path: "{{ local_mount_path }}"
    state: directory
    recurse: yes
    owner: "{{ mount_dir_user }}"
    group: "{{ mount_dir_group }}"

- name: Get escaped name for the mount unit file
  command: 'systemd-escape --path "{{ local_mount_path }}"'
  register: escaped_mount_path

- name: Install NFS mount systemd unit file
  #noinspection UndefinedVariable
  template: src=network_mount_systemd_unit_template.j2 dest=/etc/systemd/system/{{ escaped_mount_path.stdout }}.mount

- name: Mount systemd enable and start
  ansible.builtin.systemd:
    #noinspection UndefinedVariable
    name: '{{escaped_mount_path.stdout}}.mount'
    enabled: yes
    state: started


