---
- name: Create the mount directory
  ansible.builtin.file:
    path: "{{ local_mount_path }}"
    state: directory
    recurse: yes
    owner: "{{ mount_dir_user }}"
    group: "{{ mount_dir_group }}"

- name: Get escaped name for the mount unit file
  command: 'systemd-escape --path "{{ local_mount_path }}"'
  register: escaped_mount_path

- name: Install NFS mount systemd unit file
  template: src=network_mount_systemd_unit_template.j2 dest=/etc/systemd/system/{{ escaped_mount_path.stdout }}.mount

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable NFS mount service
  command: 'systemctl enable {{escaped_mount_path.stdout}}.mount'

- name: Start NFS mount service
  command: 'systemctl start {{escaped_mount_path.stdout}}.mount'

