---
- hosts: "{{ nodes }}"
  gather_facts: yes
  become: yes
  vars_files:
    - "{{ playbook_dir }}/config/*.yml"
  roles:
    - role: environment-setup
    - role: container-stack-reverse-proxy
    - role: container-stack-media-server
    - role: container-stack-management
    - role: container-stack-monitoring
