---
server_timezone: "{{ gv_server_timezone }}"
# User
server_data_dir_user: "{{ gv_local_media_user }}"
server_data_dir_uid: "{{ gv_local_media_uid }}"
server_data_dir_group: "{{ gv_local_media_group }}"
server_data_dir_gid: "{{ gv_local_media_gid }}"

# Container stack
container_data_root: "{{ gv_container_data_root }}"
reverse_proxy_container_stack_location: "{{ gv_local_media_user_home }}/.container-stack-reverse_proxy"

# Swag
reverse_proxy_config_path: "{{ container_data_root }}/reverse_proxy/config"
server_domain_name: "{{ gv_server_domain_name }}"
notification_email: "{{ gv_notification_email }}"
