---
server_timezone: "{{ gv_server_timezone }}"

# User
server_data_dir_user: "{{ gv_local_media_user }}"
server_data_dir_uid: "{{ gv_local_media_uid }}"
server_data_dir_group: "{{ gv_local_media_group }}"
server_data_dir_gid: "{{ gv_local_media_gid }}"

add_vpn_container: "{{ gv_add_vpn_container }}"

# Docker network setup
docker_bridge_network_name: "{{ gv_docker_bridge_network_name }}"

# Container stack
container_data_root: "{{ gv_container_data_root }}"
reverse_proxy_container_stack_location: "{{ gv_local_media_user_home }}/.container-stack-reverse_proxy"

# swag
swag_config_path: "{{ container_data_root }}/swag/config"
server_domain_name: "{{ gv_server_domain_name }}"
notification_email: "{{ gv_notification_email }}"

# heimdall
heimdall_config_path: "{{ container_data_root }}/heimdall/config"

# duckdns
duckdns_config_path: "{{ container_data_root }}/duckdns/config"
duckdns_token: "{{ gv_duckdns_token }}"
