---
- name: Create stack root directory
  file:
    path: "{{ management_container_stack_location }}"
    state: directory
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Copy Docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ management_container_stack_location }}/docker-compose.yml"
    owner: "{{ server_data_dir_user }}"
    group: "{{ server_data_dir_group }}"

- name: Start Docker containers using docker-compose
  community.docker.docker_compose:
    project_src: "{{ management_container_stack_location }}"
