---
server_timezone: "{{ gv_server_timezone }}"

# User
server_data_dir_user: "{{ gv_local_media_user }}"
server_data_dir_group: "{{ gv_local_media_group }}"
server_data_user_uid: "{{ gv_local_media_uid }}"
server_data_group_gid: "{{ gv_local_media_gid }}"

# Docker network setup
docker_bridge_network_name: "{{ gv_docker_bridge_network_name }}"

# Container stack
container_data_root: "{{ gv_container_data_root }}"
media_server_container_stack_location: "{{ gv_local_media_user_home }}/.container-stack-media-server"

## transmission
transmission_enable: "{{ gv_transmission_enable }}"
transmission_container_name: transmission
transmission_config_path: "{{ container_data_root }}/{{ transmission_container_name }}/config"
transmission_download_path: "{{ gv_media_data_root_local_mount_path }}/downloads"

## qbittorrent
qbittorrent_enable: "{{ gv_qbittorrent_enable }}"
qbittorrent_container_name: qbittorrent
qbittorrent_config_path: "{{ container_data_root }}/{{ qbittorrent_container_name }}/config"
qbittorrent_download_path: "{{ gv_media_data_root_local_mount_path }}/downloads"

## nordvpn
add_vpn_container: "{{ gv_add_vpn_container }}"
VPN_USERNAME: "{{ GV_VPN_USERNAME }}"
VPN_PASSWORD: "{{ GV_VPN_PASSWORD }}"
VPN_NETWORK_ALLOW_CIDR: "{{ GV_VPN_NETWORK_ALLOW_CIDR }}"
vpn_container_name: vpn

# sonarr
sonarr_config_path: "{{ container_data_root }}/sonarr/config"
sonarr_library_path: "{{ gv_media_data_root_local_mount_path }}/data/movies"
sonarr_download_path: "{{ gv_media_data_root_local_mount_path }}/downloads"

# radarr
radarr_config_path: "{{ container_data_root }}/radarr/config"
radarr_library_path: "{{ gv_media_data_root_local_mount_path }}/data/movies"
radarr_download_path: "{{ gv_media_data_root_local_mount_path }}/downloads"

# jackett
jackett_config_path: "{{ container_data_root }}/jackett/config"
jackett_torrent_file_path: "{{ container_data_root }}/jackett/torrent_files"

