---
- hosts: nodes
  gather_facts: yes
  become: yes
  roles:
    - role: environment-setup
    - role: container-stack-media-server
    - role: container-stack-management
    - role: container-stack-monitoring
    - role: container-stack-reverse-proxy
