---
# NFS
server_data_nfs_server_address: "{{ gv_nfs_server_address }}"
remote_server_data_path: "{{ gv_server_data_remote_path }}"
local_server_data_path: "{{ gv_server_data_root_mount_path }}"

# User
server_data_dir_user: "{{ gv_local_media_user }}"
server_data_dir_group: "{{ gv_local_media_group }}"
server_data_user_uid: "{{ gv_local_media_uid }}"
server_data_group_gid: "{{ gv_local_media_gid }}"

# Container stack
container_data_root: "{{ gv_server_data_root_mount_path }}/{{ container_data_dir_name | default('container_data') }}"
media_server_container_stack_location: "{{ gv_local_media_user_home }}/.container-stack-media-server"

## transmission
TRANSMISSION_USERNAME: "{{ GV_TRANSMISSION_USERNAME}}"
TRANSMISSION_PASSWORD: "{{ GV_TRANSMISSION_PASSWORD }}"
TRANSMISSION_RPC_WHITELIST: "{{ GV_TRANSMISSION_RPC_WHITELIST }}"
transmission_container_name: transmission
transmission_config_path: "{{ container_data_root }}/{{ transmission_container_name }}/config"
transmission_download_path: "{{ gv_media_download_path }}"

## qbittorrent
qbittorrent_enable: false
qbittorrent_container_name: qbittorrent
qbittorrent_config_path: "{{ container_data_root }}/{{ qbittorrent_container_name }}/config"
qbittorrent_download_path: "{{ gv_media_download_path }}"

## nordvpn
VPN_USERNAME: "{{ GV_VPN_USERNAME }}"
VPN_PASSWORD: "{{ GV_VPN_PASSWORD }}"
VPN_NETWORK_ALLOW_CIDR: "{{ GV_VPN_NETWORK_ALLOW_CIDR }}"
vpn_container_name: vpn

